<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container5m998yZ\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container5m998yZ/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container5m998yZ.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\Container5m998yZ\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \Container5m998yZ\srcDevDebugProjectContainer(array(
    'container.build_hash' => '5m998yZ',
    'container.build_id' => '781c6ebe',
    'container.build_time' => 1526666656,
), __DIR__.\DIRECTORY_SEPARATOR.'Container5m998yZ');
