<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKFlqraI\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKFlqraI/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKFlqraI.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKFlqraI\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerKFlqraI\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'KFlqraI',
    'container.build_id' => '3e67adbf',
    'container.build_time' => 1526722198,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKFlqraI');
